#!/bin/bash

. utils.sh

header 'Multi tenancy'
execute "step-04-DOCKER.sh" "Starting the docker environment"
execute "step-05-LIST_TOPICS.sh" "Listing topics in kafka1"
execute "step-06-CREATE_VIRTUAL_CLUSTER.sh" "Creating virtual cluster london"
execute "step-07-CREATE_VIRTUAL_CLUSTER.sh" "Creating virtual cluster paris"
execute "step-08-CREATE_TOPICS.sh" "Creating topic londonTopic on london"
execute "step-09-CREATE_TOPICS.sh" "Creating topic parisTopic on paris"
execute "step-10-LIST_TOPICS.sh" "Listing topics in london"
execute "step-11-LIST_TOPICS.sh" "Listing topics in paris"
execute "step-12-PRODUCE.sh" "Producing 1 message in londonTopic"
execute "step-13-CONSUME.sh" "Consuming from londonTopic"
execute "step-14-PRODUCE.sh" "Producing 1 message in parisTopic"
execute "step-15-CONSUME.sh" "Consuming from parisTopic"
execute "step-16-CREATE_TOPICS.sh" "Creating topic existingLondonTopic on kafka1"
execute "step-17-PRODUCE.sh" "Producing 1 message in existingLondonTopic"
execute "step-18-SH.sh" "Map the existing topic to the virtual cluster"
execute "step-19-LIST_TOPICS.sh" "Listing topics in london"
execute "step-20-CREATE_TOPICS.sh" "Creating topic existingSharedTopic on kafka1"
execute "step-21-PRODUCE.sh" "Producing 1 message in existingSharedTopic"
execute "step-22-SH.sh" "Map the existing topic to the virtual cluster"
execute "step-23-LIST_TOPICS.sh" "Listing topics in london"
execute "step-24-CONSUME.sh" "Consuming from existingLondonTopic"
execute "step-25-CONSUME.sh" "Consuming from existingSharedTopic"
execute "step-26-SH.sh" "Map the existing topic to the virtual cluster"
execute "step-27-LIST_TOPICS.sh" "Listing topics in paris"
execute "step-28-CONSUME.sh" "Consuming from existingSharedTopic"
execute "step-29-DOCKER.sh" "Tearing down the docker environment"
