version: '3.7'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_REPLICATION_FACTOR: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG4J_LOGGERS: "kafka.authorizer.logger=INFO"
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN

  kafka2:
    image: confluentinc/cp-kafka:latest
    hostname: kafka2
    container_name: kafka2
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093
      KAFKA_REPLICATION_FACTOR: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG4J_LOGGERS: "kafka.authorizer.logger=INFO"
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN

  conduktor-proxy:
    image: conduktor/conduktor-proxy:1.0.4_rc1-amd64
    hostname: conduktor-proxy
    container_name: conduktor-proxy
    depends_on:
      - kafka1
    ports:
      - "6969:6969"
      - "6970:6970"
      - "9999:9999"
      - "8888:8888"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka1:9092
      AUTHENTICATION_AUTHENTICATOR_TYPE: SASL_PLAIN
      USER_POOL_TYPE: JWT
      USER_POOL_SECRET_KEY: OaM4lG+xO5Gz10GB1apZ2XDUuWw/sK1H+XXcgExpYm2YEHgnvEf63q9TJraebD3SQb/JzefcZkUEKz/8V5V+Fg==
      PROXY_HOST: conduktor-proxy
      SCHEMA_REGISTRY_HOST: http://schema-registry:8081
      INTERCEPTOR_CONFIG_LOCATION: "~"
      FEATURE_FLAGS_JWT_TOKEN_ENDPOINT: true
      ADMIN_API_USERS: "[{username: superUser, password: superUser, admin: true}]"
      ADMIN_API_SECRET: OaM4lG+xO5Gz10GB1apZ2XDUuWw/sK1H+XXcgExpYm2YEHgnvEf63q9TJraebD3SQb/JzefcZkUEKz/8V5V+Fg==
      JAVA_TOOL_OPTIONS: -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.rmi.port=9999 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1
      DOWNSTREAM_THREAD: 10

  conduktor-platform:
    image: conduktor/conduktor-platform:1.14.0
    hostname: platform
    container_name: platform
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: "./platform-config.yaml"
        target: /opt/conduktor/platform-config.yaml
        read_only: true
    depends_on:
      - kafka1
    environment:
      CDK_IN_CONF_FILE: /opt/conduktor/platform-config.yaml
      KAFKA_BOOTSTRAP_SERVER: kafka1:9092
      ORGANISATION_NAME: "conduktor"
      ADMIN_EMAIL: "test@conduktor.io"
      ADMIN_PSW: "password1"
      LONDON_TOKEN: eyJhbGciOiJIUzUxMiJ9.eyJ1c2VybmFtZSI6ImxvbmRvbiIsInRlbmFudCI6ImxvbmRvbiIsImV4cCI6MTY5MTU4NDIwOH0.DbHmjG2PscVJiWx8DGSYT4QE1cZRpxgwk_T_EpmLYN4oofjL3QxlvQ3KRpGAl9QA1M6ZElY6helQKWDqQKf-YQ
      PARIS_TOKEN: eyJhbGciOiJIUzUxMiJ9.eyJ1c2VybmFtZSI6InBhcmlzIiwidGVuYW50IjoicGFyaXMiLCJleHAiOjE2OTE1ODQyMjh9.DAL6zSImURcwHjXXkohNThJRiK8QrgES_sUzCZyD7MT9fdezqOKGK4YPlw3q4Nhhlaf5_BRiWCDC3kMIQAGQ-w

  kafka-client:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-client
    container_name: kafka-client
    command: sleep infinity
    volumes:
      - type: bind
        source: "./clientConfig"
        target: /clientConfig
        read_only: true