organization:
  name: "conduktor"

admin:
  email: "bob@conduktor.io"
  password: "admin"

clusters:
  - id: default
    name: kafka-backing-cluster
    color: "#0013E7"
    ignoreUntrustedCertificate: false
    bootstrapServers: "kafka1:9092"
    properties:
    schemaRegistry:
      url: "http://schema-registry:8081"
      ignoreUntrustedCertificate: false
      properties:
    labels: {}
  - id: cdk-gateway
    name: cdk-gateway
    color: "#A020F0"
    ignoreUntrustedCertificate: false
    bootstrapServers: "conduktor-gateway:6969"
    schemaRegistry:
      url: "http://schema-registry:8081"
      ignoreUntrustedCertificate: false
      properties:
    properties: |
      security.protocol=SASL_PLAINTEXT
      sasl.mechanism=PLAIN
      sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="someTenant" password="eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InNvbWVVc2VyIiwidGVuYW50Ijoic29tZVRlbmFudCIsImV4cCI6MjAwNTcwMTQ5NX0.wrkPDqHudQXvoPMkV8nHiRxs-fck9XHzJMoWX05rU6I";
    labels: { }
  
license: