#!/bin/sh

. utils.sh

header 'Safeguard'
execute "step-04-DOCKER.sh" "Starting the docker environment"
execute "step-05-CREATE_VIRTUAL_CLUSTER.sh" "Creating virtual cluster \`teamA\`"
execute "step-07-CREATE_TOPICS.sh" "Creating topic \`cars\` on \`teamA\`"
execute "step-08-PRODUCE.sh" "Producing 3 messages in \`cars\`"
execute "step-09-CONSUME.sh" "Consume the \`cars\` topic"
execute "step-10-DESCRIBE_TOPICS.sh" "Describing topic \`cars\`"
execute "step-11-ADD_INTERCEPTOR.sh" "Adding interceptor \`guard-on-create-topic\`"
execute "step-12-LIST_INTERCEPTORS.sh" "Listing interceptors for \`teamA\`"
execute "step-13-CREATE_TOPICS.sh" "Create a topic that is not within policy"
execute "step-14-CREATE_TOPICS.sh" "Let's now create it again, with parameters within our policy"
execute "step-15-ADD_INTERCEPTOR.sh" "Adding interceptor \`guard-on-alter-topic\`"
execute "step-16-ALTER_TOPICS.sh" "Update 'cars' with a retention of 60 days"
execute "step-17-ALTER_TOPICS.sh" "Update 'cars' with a retention of 3 days"
execute "step-18-ADD_INTERCEPTOR.sh" "Adding interceptor \`guard-on-produce\`"
execute "step-19-PRODUCE.sh" "Produce sample data to our \`cars\` topic without the right policies"
execute "step-20-PRODUCE.sh" "Produce sample data to our \`cars\` topic that complies with our policy"
execute "step-21-ADD_INTERCEPTOR.sh" "Adding interceptor \`produce-rate\`"
execute "step-22-PRODUCE.sh" "Produce sample data"
execute "step-23-AUDITLOG.sh" "Check in the audit log that produce was throttled"
execute "step-24-REMOVE_INTERCEPTORS.sh" "Remove interceptor \`produce-rate\`"
execute "step-25-ADD_INTERCEPTOR.sh" "Adding interceptor \`consumer-group-name-policy\`"
execute "step-26-CONSUME.sh" "Consuming from \`cars\`"
execute "step-27-AUDITLOG.sh" "Check in the audit log that fetch was denied"
execute "step-28-CONSUME.sh" "Consuming from \`cars\`"
execute "step-29-REMOVE_INTERCEPTORS.sh" "Remove interceptor \`consumer-group-name-policy\`"
execute "step-30-ADD_INTERCEPTOR.sh" "Adding interceptor \`guard-limit-connection\`"
execute "step-31-CONSUME.sh" "Consuming from \`cars\`"
execute "step-32-AUDITLOG.sh" "Check in the audit log that connection was denied"
execute "step-33-REMOVE_INTERCEPTORS.sh" "Remove interceptor \`guard-limit-connection\`"
execute "step-34-ADD_INTERCEPTOR.sh" "Adding interceptor \`guard-agressive-auto-commit\`"
execute "step-35-CONSUME.sh" "Consuming from \`cars\`"
execute "step-36-AUDITLOG.sh" "Check in the audit log that connection was denied"
execute "step-37-DOCKER.sh" "Tearing down the docker environment"
