#!/bin/bash

. utils.sh

header 'Safeguard'
execute "step-04-DOCKER.sh" "Starting the docker environment"
execute "step-05-CREATE_VIRTUAL_CLUSTER.sh" "Creating virtual cluster teamA"
execute "step-06-CREATE_TOPICS.sh" "Creating topic cars on teamA"
execute "step-07-PRODUCE.sh" "Producing 3 messages in cars"
execute "step-08-CONSUME.sh" "Consume the cars topic"
execute "step-09-DESCRIBE_TOPICS.sh" "Describing topic cars"
execute "step-10-ADD_INTERCEPTOR.sh" "Adding interceptor guard-on-create-topic"
execute "step-11-LIST_INTERCEPTORS.sh" "Listing interceptors for teamA"
execute "step-12-CREATE_TOPICS.sh" "Create a topic that is not within policy"
execute "step-13-CREATE_TOPICS.sh" "Let's now create it again, with parameters within our policy"
execute "step-14-ADD_INTERCEPTOR.sh" "Adding interceptor guard-on-alter-topic"
execute "step-15-ALTER_TOPICS.sh" "Update 'cars' with a retention of 60 days"
execute "step-16-ALTER_TOPICS.sh" "Update 'cars' with a retention of 3 days"
execute "step-17-ADD_INTERCEPTOR.sh" "Adding interceptor guard-on-produce"
execute "step-18-PRODUCE.sh" "Produce sample data to our cars topic without the right policies"
execute "step-19-PRODUCE.sh" "Produce sample data to our cars topic that complies with our policy"
execute "step-20-ADD_INTERCEPTOR.sh" "Adding interceptor produce-rate"
execute "step-21-PRODUCE.sh" "Produce sample data"
execute "step-22-AUDITLOG.sh" "Check in the audit log that produce was throttled"
execute "step-23-REMOVE_INTERCEPTORS.sh" "Remove interceptor produce-rate"
execute "step-24-ADD_INTERCEPTOR.sh" "Adding interceptor consumer-group-name-policy"
execute "step-25-CONSUME.sh" "Consuming from cars"
execute "step-26-AUDITLOG.sh" "Check in the audit log that fetch was denied"
execute "step-27-CONSUME.sh" "Consuming from cars"
execute "step-28-REMOVE_INTERCEPTORS.sh" "Remove interceptor consumer-group-name-policy"
execute "step-29-ADD_INTERCEPTOR.sh" "Adding interceptor guard-limit-connection"
execute "step-30-CONSUME.sh" "Consuming from cars"
execute "step-31-AUDITLOG.sh" "Check in the audit log that connection was denied"
execute "step-32-REMOVE_INTERCEPTORS.sh" "Remove interceptor guard-limit-connection"
execute "step-33-ADD_INTERCEPTOR.sh" "Adding interceptor guard-agressive-auto-commit"
execute "step-34-CONSUME.sh" "Consuming from cars"
execute "step-35-AUDITLOG.sh" "Check in the audit log that connection was denied"
execute "step-36-DOCKER.sh" "Tearing down the docker environment"
