organization:
  name: "conduktor"

admin:
  email: "bob@conduktor.io"
  password: "admin"

clusters:
  - id: default
    name: gateway-backing-cluster
    color: "#0013E7"
    ignoreUntrustedCertificate: false
    bootstrapServers: "kafka1:9092"
    properties:
    schemaRegistry:
      url: "http://schema-registry:8081"
      ignoreUntrustedCertificate: false
      properties:
    labels: {}
  - id: london
    name: london
    color: "#A020F0"
    ignoreUntrustedCertificate: false
    bootstrapServers: "conduktor-proxy:6969"
    schemaRegistry:
      url: "http://schema-registry:8081"
      ignoreUntrustedCertificate: false
      properties:
    properties: |
      security.protocol=SASL_PLAINTEXT
      sasl.mechanism=PLAIN
      sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="london" password="${LONDON_TOKEN}";
    labels: { }
  - id: paris
    name: paris
    color: "#B020F0"
    ignoreUntrustedCertificate: false
    bootstrapServers: "conduktor-proxy:6969"
    schemaRegistry:
      url: "http://schema-registry:8081"
      ignoreUntrustedCertificate: false
      properties:
    properties: |
      security.protocol=SASL_PLAINTEXT
      sasl.mechanism=PLAIN
      sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="london" password="${PARIS_TOKEN}";
    labels: { }

license: